version: '3.9'
services:
  api-gateway:
        build: api-gateway
        environment: 
            USER_SERVICE_HOST: 'user-service:9001'
            PRODUK_SERVICE_HOST: 'produk-service:9002'
        ports:        
          - "9000:9000"
        depends_on:
          - user-service
          - produk-service
        restart: always
  produk-service:
      build: produk-service
      environment: 
          MYSQL_HOST: 'mysql:3306'
          MYSQL_DATABASE: 'nidzam-ecomerce'
          MYSQL_USER: 'root'
          MYSQL_PASSWORD: 'password'
      # ports:        
      #   - "9000:9000"
      depends_on:
        - mysql
      restart: always
  user-service:
      build: user-service
      environment: 
          MYSQL_HOST: 'mysql:3306'
          MYSQL_DATABASE: 'nidzam-ecomerce'
          MYSQL_USER: 'root'
          MYSQL_PASSWORD: 'password'
      # ports:        
      #   - "9000:9000"
      depends_on:
        - mysql
      restart: always
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'nidzam-ecomerce'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root'
      MYSQL_HOST: 'localhost:3306'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
    expose:
      - "3306"
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: